package uz.pdp.backend.enums;

public enum Status {
    STARTED,
    CHOOSE_LANGUAGE,
    SHARE_PHONE_NUMBER,
    MAIN_MENU,
    SETTINGS,
    ORDER_MENU,
    BUSINESS_APPLICATION_MENU,
    OPEN_BUSINESS_APPLICATION,
    SET_LANGUAGE,
    SET_PHONE_NUMBER,
    CHECK_BUSINESS_APPLICATION_MENU,
    CHECK_COURIER_APPLICATION_MENU,
    WRITING_COMMENT_MENU,
    CHOOSE_APPLICATION_TYPE_MENU,
    COURIER_APPLICATION_MENU,
    ADD_PRODUCT_BUSINESSMAN,
    CHOOSE_BUSINESS,
    CHOOSE_CATEGORY,
    CHECK_REPORTS,
    CHOOSE_TYPE_OF_EDITING,
    EDIT_BUSINESS_NAME,
    EDIT_BUSINESS_LOCATION
}
